name = "wikis-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_id = "12a8066add24d9c643e7c6186b5659c2" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
